export class AssetsDB {
    public assets = [
        {
            'id': 1,
            'name': 'OTR-1000',
            'status': 'Stand Still',
            'state': 'Standby',
            'wellsite': 'none',
        },
        {
            'id': 2,
            'name': 'OTR-1001',
            'status': 'At Well site',
            'state': false,
            'wellsite': 'Gusher',
        },
        {
            'id': 3,
            'name': 'OTR-1002',
            'status': 'Picking up chemical',
            'state': 'Moving',
            'wellsite': 'Gusher',
        },
        {
            'id': 4,
            'name': 'OTR-1003',
            'status': 'Picking up chemical',
            'state': 'Moving',
            'wellsite': 'Big Flow',
        },
        {
            'id': 5,
            'name': 'OTR-1004',
            'status': 'Stand Still',
            'state': 'Standby',
            'wellsite': 'none',
        },
        {
            'id': 6,
            'name': 'OTR-1005',
            'status': 'Going to wellsite',
            'state': 'Moving',
            'wellsite': 'Big Flow',
        },
        {
            'id': 7,
            'name': 'OTR-1006',
            'status': 'Going to wellsite',
            'state': 'Moving',
            'wellsite': 'Gusher',
        },
        {
            'id': 8,
            'name': 'OTR-1007',
            'status': 'Stand Still',
            'state': 'Standby',
            'wellsite': 'none',
        },
        {
            'id': 9,
            'name': 'OTR-1008',
            'status': 'Picking up chemical',
            'state': 'Moving',
            'wellsite': 'Big Flow',
        },
        {
            'id': 10,
            'name': 'OTR-1009',
            'status': 'At well site',
            'state': 'Stand Still' ,
            'wellsite': 'Gusher',
        },
        {
            'id': 11,
            'name': 'OTR-1010',
            'status': 'Picking up chemical',
            'state': 'Moving',
            'wellsite': 'Big Flow',
        },
    ]
}
